### PR TITLE
Conditional comments for script references

### PR DESCRIPTION
**Pull request by jimmah**
Hi Andrew,

I needed to include certain scripts only for certain versions of IE, e.g. HTML5 shim for versions of IE < 9. I copied the Condition functionality from the Stylesheet bundles to the Script bundles.

Not sure if you want this in cassette, but feel free to use it if its of any use.

### CODE REVIEW

**Comment by andrewdavey** [comment]
Very nice, thank you!

Can you also enhance `ScriptBundleManifestReader` and `ScriptBundleManifestWriter` so the condition will be persisted in the cache manifest too? Otherwise loading from cache in production mode will lose the condition.

Do we also need this for ExternalScriptBundle?

**Comment by jimmah** [comment]
Modified ScriptBundleManifestReader / Writer as requested.

Also, added Conditional comments for ExternalScriptBundle.

Hope this is of some use!

**Comment by andrewdavey** [comment]
Excellent, thank you for all this! I'll get this merged in soon.

**Comment by andrewdavey** [comment]
This has been merged into `master` and will be in the next release.
Thanks again for this excellent addition to Cassette.

**Pull request closed without merging**
