### PR TITLE
Remove dependency on System.Web from main Cassette module

### PR DESCRIPTION
**Pull request by ChrisMH**
Andrew,

I've become a fan of the Nancy framework, but don't like the current way that static content is handled.  I have started working on an integration module to pull Cassette into the Nancy pipeline : https://github.com/ChrisMH/Nancy.Cassette

The first step was to remove any reference to System.Web and related namespaces from the main Cassette project.  The project in this pull request is now based on the .NET 4.0 client profile and does not use any reference to ASP.NET libraries.

I used some code from the Mono project (JSON Serialization, HttpUtility), and I replaced IHttpString/HttpString with string.  I didn't see a reason that interface/class was necessary, but perhaps I'm missing something.

Unit tests were updated and are passing (except for two which didn't pass before I made these changes).

Chris

### CODE REVIEW

**Comment by andrewdavey** [comment]
Awesome work Chris, thank you! Andreas will be happy too :)

The IHtmlString was being used so that generated HTML elements were not html-encoded by razor when put into the page. However, it's seems reasonable to just add the HtmlString wrapper around the normal strings in the Cassette.Web's Render helper method.

I'll try to get this merged into my 1.0 branch asap. Thanks again!

**Comment by andrewdavey** [comment]
I just realised that what I said doesn't make any sense!! The Assets helper is in the main Cassette assembly. We can perhaps move it to the Cassette.Web assembly. The Nancy assembly would then need it's own version of the helper.

**Comment by ChrisMH** [comment]
I'm still coming up to speed on the Nancy & Cassette pipelines, but if I'm not mistaken, the Assets helpers write GUIDs into the HTML which are then replaced later on with references (in PlaceholderReplacingResponseFilter).  That code doesn't have anything to do with Razor and appears to just be a direct string replace.

**Comment by andrewdavey** [comment]
When HTML rewriting is enabled (the default) then GUIDs are inserted into the page and replaced later with the actual HTML. When rewriting is disabled the actual HTML is inserted directly. So without the IHtmlString wrapper, Razor will HTML encode the generated HTML. So the in-page helpers still need to using IHtmlString.

An option I'm exploring now is moving the static in-page helper into Cassette.Web. This will mean Cassette's core public API can be free of any System.Web types. The core Cassette HTML generators can be converted to return raw strings (as per your commit). However, Cassette.Nancy will then require its own static helper class. Is this a problem?

I'm also a bit concerned about pulling in all that mono source. It means we have to track the original source and support it within Cassette (apply patches, etc). How about using Json.net instead? That works with the .net client profile and has a nuget package.

HttpUtility is only used in one place by Cassette (BundleCache) and I'm pretty sure that code path is actually never hit! Deleting that code then removes the final System.Web dependency.

**Comment by andrewdavey** [comment]
I'm going to create a new assembly `Cassette.Views`, which will contain the static in-page helpers. It will use IHtmlString and therefore depend on `System.Web`.
The `Cassette.Web` assembly will depend on `Cassette.Views`.

This means someone can use `Cassette.Views` from a Nancy app (assuming they don't mind the system.web dependency). In the extreme case that someone can't reference system.web, it's easy to create a similar helper API that matches Cassette's helpers, but uses only strings.

**Comment by ChrisMH** [comment]
Makes sense.  A Nancy app using Razor views is dependent on System.Web anyway, so it shouldn't be a problem.

I pulled in the Mono source because I didn't want to add a direct external dependency to your project.  If you don't mind that, Json.net is a good choice.  I've used it before and I think it's better than the Json libraries in System.Web.

**Comment by andrewdavey** [comment]
Cool, let's go with Json.net.

I've pushed the branch here https://github.com/andrewdavey/cassette/tree/remove-system-web-dependency - it's based on the forthcoming 1.0 beta. I'm unsure how easy it'll be to merge with your current Nancy.Cassette fork. Once 1.0 is done it may be easier for us to go through your code and cherry pick for a new Nancy integration library.

**Comment by ChrisMH** [comment]
Nancy.Cassette didn't turn into all that much code, so it should be fairly
easy.  I'll rebase this evening and see.

**Pull request closed without merging**
