### PR TITLE
#152 - AddFile<T> Single File support

### PR DESCRIPTION
**Pull request by drlongnecker**
So far, this seems to be the ticket for single file support. Compiled and been using the code on an the bootstrap.less file that originally spawned the issue and things seem solid. Let me know if I've missed anything and I'll toss it up.

Thanks!

-dl

### CODE REVIEW

**Comment by andrewdavey** [comment]
D'oh, I just realised that the existing `Add` method has support for single files! Sorry to waste your time here! I'll have to owe you a beer.

Can you confirm that the existing `Add` method works for your Less file?

**Comment by drlongnecker** [comment]
Hmm, I tried that before... I get:

Bundle path not found: styles/libs/bootstrap.less

Exception Details: System.IO.DirectoryNotFoundException: Bundle path not found: styles/libs/bootstrap.less

@ line: `bundles.Add<StylesheetBundle>("styles/libs/bootstrap.less");`

Am I that calling it correctly or is there other voodoo to specify a single file?

**Comment by andrewdavey** [comment]
It shouldn't require any voodoo, your call looks okay to me.

Can you break-point on line 76 of `BundleCollectionExtensions.cs` (`var file = source.GetFile(applicationRelativePath);`) and step into that call to see why it thinks the file does not exist?

I'll do some more testing here too.

**Comment by andrewdavey** [comment]
Is the path correct?

e.g. is there a folder missing?

```
bundles.Add<StylesheetBundle>("styles/libs/bootstrap/bootstrap.less");
```

**Comment by drlongnecker** [comment]
Why yes, yes there is... _facepalm_ Eesh, trying to code during meetings is fail. Okay, with that, I now get a different error...

The asset file "styles/libs/bootstrap/bootstrap.less" was not found for bundle "~/styles/libs/bootstrap/bootstrap.less".

Breaking on the the line, I get:

file.Exists true
file.FullPath   "~/styles/libs/bootstrap/bootstrap.less"

It then dies on the next line to create the Bundle. Digging deeper in, it throws a `FileNotFoundException` at line 54.

https://github.com/andrewdavey/cassette/blob/master/src/Cassette/BundleFactoryBase.cs#L54-65

The incoming fileName doesn't have the ~/ whereas the key in the filesByPath does.

**Comment by andrewdavey** [comment]
;) no worries. I'm having a very similar day here!

My guess is that prefixing the path with a `~/` will fix it for now:

```
bundles.Add<StylesheetBundle>("~/styles/libs/bootstrap/bootstrap.less");
```

I'm looking into a proper fix at the moment...

**Comment by drlongnecker** [comment]
Yep, that works like a champ.

Looks like if it wrapped the descriptor lines in:

https://github.com/andrewdavey/cassette/blob/master/src/Cassette/Configuration/BundleCollectionExtensions.cs#L103-106

back around through PathUtilities.AppRelative... it should catch that... maybe.

**Comment by andrewdavey** [comment]
Yes, I think so too. I'm going to put the `AppRelative` call at the top of the `Add` function, just to be sure :)
Commit to follow in a few minutes...

**Comment by drlongnecker** [comment]
That's the winner. Works like a champ.

**Comment by andrewdavey** [comment]
Cool, thanks for helping with this. Much appreciated!

Closing this pull request now that `Add` works correctly for individual file.

We'll probably want a new issue to track the progress of ensuring Less `@import`s result in the proper Cassette asset file references...

**Comment by drlongnecker** [comment]
Yeah. My plan was to dig into the parser code later and find out why those
mixins fail. I'll make an issue and run with that.

**Pull request closed without merging**
