### PR TITLE
V2 with internal jsonserializer

### PR DESCRIPTION
**Pull request by albertjan**
borrowed from nancy. I may have accidentally deleted the reference to iesi collections aswell can you fix that or should I do a new pull-req.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
+1, i think cassette should not take dependency on Newtonsoft.Json. 

Or you could also try a single file `SimpleJson.cs` https://github.com/facebook-csharp-sdk/simple-json `Install-Package SimpleJson`. We heavily use it embedded in facebook-c#-sdk

**Comment by andrewdavey** [comment]
Cassette v2 is now using SimpleJson

**Comment by prabirshrestha** [comment]
awesome.

@andrewdavey just a side note. I would recommend you to change the namespace for SimpleJson to Cassette incase some other libraries embeds SimpleJson with the same namespace and uses reflections even though it is internal. If you are using nuget to install SimpleJson, it automatically sets the namespace by using `$rootnamespace$`.

**Comment by andrewdavey** [comment]
Good idea - done :)

**Pull request closed without merging**
