### PR TITLE
RegisterTemplateWithJQueryTmpl no longer assumes the $ alias for jQuery

### PR DESCRIPTION
**Pull request by willholley**
fix for #243. Use jQuery explicitly in global scope.

### CODE REVIEW

**Comment by andrewdavey** [comment]
It seems this pull request has gained some extra commits that are unrelated. So I've simply applied the two small changes by hand directly into `v2`.
Thanks for the fix though!

**Comment by willholley** [comment]
Apologies - still getting used to managing branches for different issues. I think I'm on top of it now though!

**Comment by andrewdavey** [comment]
No worries :) I really appreciate all the time you've been putting into Cassette. Thanks again!

**Comment by willholley** [comment]
Not a problem - we're committed to it now at Bluewire and we're using
many of the additional packages (Jasmine and Knockout support) so will
push back patches as we find issues. We're planning to use v2 (with
our patches) in production in the next week or so.

I know the pull request got messed up - would it be possible to merge
in https://github.com/andrewdavey/cassette/commit/0eb635ba2238316adbc849b506d8830624638ecc?
Without it there's no way for us to use the official package until VS
11 / IIS express 64-bit because we rely on cassinidev for 64-bit web
development.

On 18 May 2012 08:05, Andrew Davey
reply@reply.github.com
wrote:

**Comment by andrewdavey** [comment]
Sure thing - I've merged and pushed that commit.

**Pull request closed without merging**
