### PR TITLE
HtmlAttribute Functionality added to bundle

### PR DESCRIPTION
**Pull request by tomdenny**
The bundle supports the HtmlAttribute property and can be set using an object in much the same fashion that MVC HtmlHelpers work.  `bundle.HtmlAttributes = new { @class = "myClass", async = "async" }`

I made a few decisions that I'd like to call out in case you have a difference of opinion on them:

1) Lazy load the HtmlAttributeDictionary:  My thinking here is that HtmlAttributes won't be used in the majority of cases.  No sense keeping a Dictionary object around for no reason.

2) External script reference with fallback does not check to make sure the user hasn't done something odd like put a async="async" attribute on the external reference -- causing the fallback to likely execute too.

Thanks for the opportunity.
-Tom

### CODE REVIEW

**Comment by nazjunaid** [comment]
Cool

**Comment by andrewdavey** [comment]
This is great, thank you!

Here are some notes I made while looking through the code:

Re: laziness - For small objects like empty dictionaries, I'm not sure the added complexity of the code is worth the small memory saving. If you are keen to keep the underlying dictionary lazy then use a `Lazy<T>` to handle the initialization.

Re: external scripts with async - Let's allow people to run with scissors for now :)

Re: HtmlAttributes

`Bundle.HtmlAttributes` being typed as `object` will make it harder for bundle processors to add extra attributes without replacing any that were added previously. Perhaps introduce a class `HtmlAttributeDictionary` with Add method overloads like this:

```
bundle.HtmlAttributes.Add(new { @class = "myclass", async = "async" });
bundle.HtmlAttributes.Add("async"); // creates "async" -> null, useful for those nasty HTML5 attributes with no values.
bundle.HtmlAttributes.Add("class", "myclass"); // the usual dictionary Add method
```

We lose the simple assignment syntax, but I think the extra flexibility will be worth it.

This new class simplifies the `Bundle` code. It just needs a basic read-only property. Also, your dictionary helper methods can be moved into `HtmlAttributeDictionary`.

I'm unsure about making all attributes "to lower" by default. I don't think the MVC helpers do this - let me know if I'm wrong here. Also, can attributes with dashes, like `<script data-main="go">`, be generated by underscores, `new { data_main="foo" }`. Again, check with what MVC does for this.

Please let me know your thoughts on all the above. I'm looking forward to getting this feature merged in. Thanks again for this excellent contribution.

**Comment by tomdenny** [comment]
All good comments, thanks.  I'll do them tonight or tomorrow. 

I'm not set on lazy loading at all.  Out it goes!  I wasn't crazy about all the HtmlAttributesDictionary ? String.Null : ...; checks either.  Getting rid of that will certainly make the code look a lot cleaner.

Creating the HtmlAttributes type was my first thought too, but I wanted to follow MVC's htmlAttributes "object" assignment pattern.  However, I completely agree with you with respect to it restricting future uses of HtmlAttributes.  Besides, if it becomes an issue we could always add a companion write-only object property later.  Telerik uses the approach you suggest too so we wouldn't be going completely off the reservation.

Dashes aren't allowed in property names, but certainly the conversion of "-" to "_" would be useful in some of the new overloaded Add methods.

Tests:
Both Telerik and MVC convert attribute names to lower case. new { FOObar = "test' } becomes foobar="test".

**Comment by andrewdavey** [comment]
Awesome! Thanks for researching the attribute name conversion. If it's good for MVC and Telerik, then I'm happy for Cassette to work the same way :)

**Comment by tomdenny** [comment]
ready to rock --

You may have thoughts on a better namespace for HtmlAttributeDictionary to live.  I gave Cassette.Configuration and Cassette.BundleProcessing a nod before settling on Cassette.

I was too shy to expose an IDictionary interface publicly, but I gave people an IEnumerable and a few useful Dictionary-like methods.

**Comment by andrewdavey** [comment]
It looks great! I'm fine with HtmlAttributeDictionary living in the root Cassette namespace. I may add the IDictionary interface later, if my OCD gets the better of me :)

I should be able to merge this soon and have it in the v1.1 release.

Thanks!

**Comment by tomdenny** [comment]
I got your dash request wrong.  Let me fix it this morning and do another checkin.  I'll test what MVC/telerik does in that case too.

**Comment by tomdenny** [comment]
Both Telerik and MVC convert underscores in object parameter names to dashes.
Telerik has an overload that accepts an IDictionary<string, object>.  That overload does not convert underscores in the string key.

I followed the same pattern.  Sorry, I simply misunderstood your original comment.  It makes a lot more sense now.

**Comment by andrewdavey** [comment]
Awesome work - thank you!

I've merged this into master and added some extra tests, etc.

**Pull request merged**
