### PR TITLE
More Conditional Comments changes (+tests this time!)

### PR DESCRIPTION
**Pull request by thecontrarycat**
I've made changes to the way conditional comments are rendered to allow for the !IE style (see the last example at http://www.quirksmode.org/css/condcom.html ).

As the render process is the same for all types of bundle that have conditionals, I've extracted the conditional comment rendering into a separate class.

### CODE REVIEW

**Comment by andrewdavey** [comment]
Very nice, thank you.

Two points:
- Can `HasCondition` be made internal? My preference is to keep the public API as small as possible.
- Does `Bundle` need to have the `ConditionalRenderer` as a property? Can you just create an instance, when required, in each of the bundle renderers?

I'm looking forward to merging this in!

**Comment by thecontrarycat** [comment]
HasCondition can definitely be made internal.  I did feel a bit dirty having to put that into both StylesheetBundle and ScriptBundle though - could we make a ConditionalBundle abstract parent class so that the Condition and HasCondition properties are only declared in one place?  (I would have done this but I'm always nervous about making larger refactors than necessary in someone else's codebase).

No, ConditionalRenderer doesn't need to be a property on the bundle itself.  I was thinking about making it static but wasn't sure what your thoughts on static methods are, so went with the property approach.  I have no problem with it being a new instantiation at call time, static or a property - up to you!

**Comment by andrewdavey** [comment]
I'm okay with both `StylesheetBundle` and `ScriptBundle` having their own `Condition` and `HasCondition` properties. I feel that the slight duplication is cleaner than introducing an abstract base class just for them. If we ever do want to write code that dealt with `Condition` for either bundle type, then we can introduce an interface `IBundleWithCondition`, for example.

For the conditional renderer, let's go with a new instantiation at call time.

Thanks :)

**Comment by thecontrarycat** [comment]
Sounds fine to me.  Are you able to do the pull and then make the changes or should I?

**Comment by andrewdavey** [comment]
Please go ahead and make the changes. I'm very busy this week, so I'm delegating as much as possible :) thanks!

**Comment by thecontrarycat** [comment]
Andrew, I've updated the areas we discussed, but unfortunately I'm so new to git that I've managed to include an extra commit in this pull request and have no clue how to remove it.

So, this pull request now includes the preliminary mhtml support work, granting the ability to choose full data uris or IE8 restricted data uris.

Sorry :(

**Comment by andrewdavey** [comment]
That's okay, I'll cherry pick the commits as required :)

BTW: this is a handy guide for working with git when contributing to an open source project: https://github.com/NancyFx/Nancy/wiki/Git-Workflow

Thanks again for all your help.

**Pull request merged**
